### ISSUE TITLE
Interface freezes whenever turning on Log Messages panel on QGIS 3.8 flatpak image 

### ISSUE THREAD

**Issue by suricactus** [flathub/org.qgis.qgis#40] opened 2019-10-16 23:29 UTC
**Describe the bug**
The title says it all. Enabling the Log Messages panel completely freezes the UI, nothing inside the window is clickable. However, the menu is still responsive and turning off the panel works fine, the panel disappears. However, the interface remains frozen until restart. It appears that only Log Messages panel cause this. This is what is observed from the command line log:
> Warning: QXcbConnection: XCB error: 8 (BadMatch), sequence: 9238, resource id: 60817545, major code: 42 (SetInputFocus), minor code: 0

I've tried to list this on QGIS issues, but got rejected: 
https://github.com/qgis/QGIS/issues/32286

**How to Reproduce**
1. Install the flatpak image.
2. Run using `flatpak run org.qgis.qgis`
3. Either right click on the menu section and enable the Log Messages panel, or do it through (Top Menu -> ) Settings -> Panels -> Log Messages

**QGIS and OS versions**
OS -> KDE Neon, but I also experienced it before on other Ubuntu based distros under flatpak
QGIS:
```
QGIS version | 3.8.3-Zanzibar | QGIS code revision | 685d8b15
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Linux 5.0.0-31-generic |   |  


```

**Additional context**
Opening/closing the plugins windows works fine. However, closing the About windows is impossible. I didn't manage to select the text either. Turning off all plugins didn't help too.

**Comment by aleixpol** [comment] 2019-10-17 11:05
There's no reason to think this is a packaging issue. Please report to qgis.
https://github.com/qgis/QGIS/issues

**Comment by suricactus** [comment] 2019-10-17 11:47
It's not very fruitful to play the issue ping-pong game. It affects the combination of the product itself (qgis) and the platform (flatpak). I know flatpak is marked experimental, but would be nice to have it fully production ready at some point. For some users it's the only way to install recent or any version of QGIS. I'm not good enough with cpp, flatpak or qt to be able to solve this issue myself.

**Comment by aleixpol** [comment] 2019-10-17 12:34
What I'm saying is that it's an issue I don't think I can fix. Please report it to QGIS.
I'll keep working on the flatpak integration because I agree it's important too.

**Comment by suricactus** [comment] 2019-10-17 14:59
I appreciate your work. KDE Neon is not Qt friendly for non-KDE software and flatpak is the only user-friendly option.  I've opened an issue on their repo before being advised to report here https://github.com/qgis/QGIS/issues/32286 . I hope the guys from QGIS will take care of this problem, for me it's more logical the issue to come from the QGIS itself, rather than the flatpak environment.

**Comment by aleixpol** [comment] 2019-10-17 15:17
Right, I see they're not all that eager. Let's leave it open here then. If you come to find why that could be, that would be really useful.

**Comment by rduivenvoorde** [comment] 2019-12-03 14:52
Hi, just testing here, I can not reproduce this.
With me I can just open the panel and it is work fine.
Could it be an KDE / Flatpak issue?

I'm on Debian Testing, Gnome 3.34.1

QGIS version | 3.8.3-Zanzibar | QGIS code revision | 685d8b15
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.6
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Linux 5.3.0-2-amd64 |   |

**Comment by suricactus** [comment] 2019-12-07 05:27
Hi, because I was unable to use neither the flatpak version, nor the .deb one, I've switched to Kubuntu 19.10. However, the problem remains on the flatpak version. The interface is completely frozen.

I'm using KDE backports to get the latest Plasma 5.17. Is it possible for the host to somehow influence the flatpak application?

QGIS version | 3.8.3-Zanzibar | QGIS code revision | 685d8b15
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.6
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Linux 5.3.0-23-generic |   |  

I've uploaded a video how it looks like, I'm clicking the mouse all the time. Even the exit button in the title bar does not work.
https://imgur.com/a/fl5bdW4

**Comment by basilrabi** [comment] 2019-12-18 12:00
Works for me on the recent build (e9d1ad6e161942a9abf1e40c2cf9b9bb23ad0ba7). I'm using Fedora 31 with Flatpak version 1.4.3. Maybe this is related to the distro or the version of Flatpak itself? By the way, in QGIS 3.10.x, the Log Messages is now in (Top Menu)->View->Panels

**Comment by aleixpol** [comment] 2020-02-17 16:09
Works for me as well both on archlinux and kubuntu. Closing for now, please reopen if it reappears.

**Closed** 2020-02-18 01:08 UTC

**Comment by jonbar12** [comment] 2020-03-12 20:57
I have the same problems whenever the message log is opened it freezes
I am using kubuntu 18.04 and QGIS 3.10

**Comment by suricactus** [comment] 2020-03-12 21:31
I think there is something with packaging on Kubuntu 18.04, I was experiencing this on KDE neon, which is based on that specific version.
No longer an issue on 19.10, we will see how 20.04 goes.
